inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - modules/**/*
    - vendor/**/*
    - .vendor/**/*

require: rubocop-rake

Layout/LineLength:
  Max: 110
